# Generated by Django 3.1.2 on 2020-12-08 02:57

from django.db import migrations, models
import toDo.enums


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TO-DO', 'TO-DO'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED')], default=toDo.enums.StatusList['TODO'], max_length=255),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
